####################################### ROOT ROUTE #################################################

GET  http://localhost:8000/
content-type: application/json



#####################################################################################################
#                                                                                                   #
#                                          ADMIN ROTES                                              #
#                                                                                                   #
#####################################################################################################

# Root Admin Route
GET  http://localhost:8000/admin
content-type: application/json



####
# Register Admin Route
POST http://localhost:8000/admin/register
content-type: application/json

{
    "role":"Admin",
    "userName":"test1",
    "userID":"test@gmadiel.com",
    "password":"divyansh",
    "instituteName":"inst1",
    "instituteType":"Chapter",
    "instituteImage":"sample.jpeg",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "district":"Vellore",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772
}



####
# Admin Login Route
POST http://localhost:8000/admin/login
content-type: application/json

{
    "userName": "test123",
    "email":"divyanshkhandelwal@gmail.com",
    "password": "pass1"
}


####
# Get Organizations Route
GET  http://localhost:8000/admin/institutes
content-type: application/json



#####################################################################################################
#                                                                                                   #
#                                          EMPLOYEE ROTES                                           #
#                                                                                                   #
#####################################################################################################

# Root Employee Route
GET  http://localhost:8000/employee
content-type: application/json


####
# Create Employee Route
POST http://localhost:8000/employee/register
content-type: application/json

{
    "role":"Employee",
    "userName":"Divyansh1",
    "userID":"divyanshkhandelwal@gmail.com",
    "password":"password",
    "grade":"Tech head",
    "division":"Web",
    "adharNumber":123456789789,
    "contactNumber":9935071772
}


####
# Login Employee Route
POST http://localhost:8000/employee/login
content-type: application/json

{
    "email":"divyanshkhandelwal@gmail.com",
    "password": "password"
}


















#####################################################################################################
#                                                                                                   #
#                                          CUSTOMER ROTES                                           #
#                                                                                                   #
#####################################################################################################