####################################### ROOT ROUTE #################################################

GET  http://localhost:8000/
content-type: application/json


#####################################################################################################
#                                                                                                   #
#                                         SUPER ADMIN ROTES                                         #
#                                                                                                   #
#####################################################################################################

####
# Purge the Database
DELETE http://localhost:8000/superAdmin/purge
content-type: application/json


####
# Approve Admin
POST http://localhost:8000/superAdmin/approveAdmin
content-type: application/json

{
    "id": "5ee0ea50659bf815cdc6269c"
}

#####################################################################################################
#                                                                                                   #
#                                          ADMIN ROTES                                              #
#                                                                                                   #
#####################################################################################################

# Root Admin Route
GET  http://localhost:8000/admin
content-type: application/json



####
# Register Admin Route
POST http://localhost:8000/admin/register
content-type: application/json

{
    "role":"Admin",
    "userName":"admin2",
    "userID":"admin2.com",
    "password":"divyansh",
    "instituteName":"inst2",
    "instituteType":"Chapter",
    "instituteImage":"sample.jpeg",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "afafaaf"
}



####
# Get Organizations Route
GET  http://localhost:8000/admin/institutes
content-type: application/json


####
# View All Institute's Employee
POST http://localhost:8000/admin/viewAllEmployees
content-type: application/json

{
    "instituteName": "IEEE"
}



####
# Approve Employee
POST http://localhost:8000/admin/approveEmployee
content-type: application/json

{
    "id": "5ee0ea50659bf815cdc6269c"
}



####
# Reject Employee
POST http://localhost:8000/admin/rejectEmployee
content-type: application/json

{
    "id": "5ee0ea50659bf815cdc6269c"
}










#####################################################################################################
#                                                                                                   #
#                                          EMPLOYEE ROTES                                           #
#                                                                                                   #
#####################################################################################################

# Root Employee Route
GET  http://localhost:8000/employee
content-type: application/json


####
# Create Employee Route
POST http://localhost:8000/employee/register
content-type: application/json

{
    "role":"Employee",
    "userName":"b",
    "userID":"b@gmaiddl.com",
    "password":"password",
    "instituteName":"IEEE",
    "grade":"Tech head",
    "division":"Web",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "safasd"
}



####
# View Pending Customer Route
POST http://localhost:8000/employee/pendingCustomers
content-type: application/json

{
    "instituteName":"IEEE"
}


####
# View Customer Route
POST http://localhost:8000/employee/viewCustomers
content-type: application/json

{
    "employeeID":"IEEE"
}




####
# View Customer Route
POST http://localhost:8000/employee/approveCustomer
content-type: application/json

{
    "id":"SFASFaSF",
    "employeeID":"IEEE"
}



POST http://localhost:8000/employee/rejectCustomer
content-type: application/json

{
    "id":"SFASFaSF",
    "employeeID":"IEEE"
}










#####################################################################################################
#                                                                                                   #
#                                          CUSTOMER ROTES                                           #
#                                                                                                   #
#####################################################################################################


# Root Customer Route
GET  http://localhost:8000/customer
content-type: application/json


####
# Register Customer Route
POST http://localhost:8000/customer/register
content-type: application/json

{
    "role":"customer",
    "userName":"customer1",
    "userID":"customer1",
    "password":"123456",
    "grade":"sFsdg",
    "division":"sdgsdga",
    "instituteName":"agdd",
    "numberOfMembers":50,
    "mailAddress":"sdgdsg@gmil.com",
    "adharNumber":1234564564,
    "contactNumber":1234566544,
    "fcmToken": "afafsfg"
}





#####################################################################################################
#                                                                                                   #
#                                          COMMON ROTES                                             #
#                                                                                                   #
#####################################################################################################

####
# send Notifications
POST http://localhost:8000/sendNotification
content-type: application/json

{
    "fcmToken":"dItTSf1Lq5A:APA91bFhccnuE3JjCcCgdWtyuTU0UAeD7lgIRyhqY1_8x51kt1uJc2V-YHaKEBilFSv2yiKO8VetrBc790rrkp94_EmUd4JueoVEl38keHEsqJO_Rnco6r4bAolk7Tjdp2H_3n02gTRx",
    "message":"Approved"
}

####
# Login Route
POST http://localhost:8000/login
content-type: application/json

{
    "fcmToken" : "asdlkfccccccchdslf",
    "email":"customer1",
    "password": "123456"
}
