####################################### ROOT ROUTE #################################################

GET  https://app-workbook.herokuapp.com/
content-type: application/json


#####################################################################################################
#                                                                                                   #
#                                         SUPER ADMIN ROTES                                         #
#                                                                                                   #
#####################################################################################################





####
# Test Route
GET  http://localhost:8000/superAdmin
content-type: application/json



####
# Purge the Database
DELETE http://localhost:8000/superAdmin/purge
content-type: application/json


####
# Approve Admin
POST http://localhost:8000/superAdmin/approveAdmin
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48"
}

####
# Delete Admin
DELETE  http://localhost:8000/superAdmin/deleteAdmin
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48"
}


####
# Create SuperAdmin
POST http://localhost:8000/superAdmin/create
content-type: application/json

{
    "fcmToken": "sdgsg",
    "userID": "superAdmin",
    "password": "123",
    "userName": "superAdmin"
}



####
# Login Route
POST http://localhost:8000/login
content-type: application/json

{
    "fcmToken" : "asdlkfccccccchdslf",
    "userID":"superAdmin",
    "password": "123"
}
#####################################################################################################
#                                                                                                   #
#                                          ADMIN ROTES                                              #
#                                                                                                   #
#####################################################################################################

# Root Admin Route
GET  http://localhost:8000/admin
content-type: application/json



####
# Register Admin Route
POST http://localhost:8000/admin/register
content-type: application/json

{
    "role":"Admin",
    "userName":"admin2",
    "userID":"admin2.com",
    "password":"divyansh",
    "instituteName":"inst2",
    "instituteType":"Chapter",
    "instituteImage":"sample.jpeg",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "afafaaf"
}



####
# Get Organizations Route
GET  http://localhost:8000/admin/institutes
content-type: application/json


####
# View All Institute's Employee
POST http://localhost:8000/admin/viewAllEmployees
content-type: application/json

{
    "instituteName": "IEEE"
}



####
# Approve Employee
POST http://localhost:8000/admin/approveEmployee
content-type: application/json

{
    "id": "5eef66dceaad484382c4f4e9"
}



####
# Reject Employee
POST http://localhost:8000/admin/rejectEmployee
content-type: application/json

{
    "id": "5eef52404322216db5ec43a8"
}

####
# Delete Employee
POST http://localhost:8000/admin/deleteEmployee
content-type: application/json

{
    "id": "5eef66dceaad484382c4f4e9"
}



####
# Update Admin
POST http://localhost:8000/admin/update
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48",
    "userName":"admin2",
    "instituteType":"Chapter",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "afafaaf"
}


####
# Approve Driver
POST http://localhost:8000/admin/approveDriver
content-type: application/json

{
    "id": "5eefa5187416ad00177c7127"
}




#####################################################################################################
#                                                                                                   #
#                                          EMPLOYEE ROTES                                           #
#                                                                                                   #
#####################################################################################################

# Root Employee Route
GET  http://localhost:8000/employee
content-type: application/json


####
# Create Employee Route
POST http://localhost:8000/employee/register
content-type: application/json

{
    "userName":"emp",
    "userID":"emp",
    "password":"password",
    "instituteName":"IEEE",
    "grade":"Tech head",
    "division":"Web",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "safasd"
}



####
# View Customer Route
POST http://localhost:8000/employee/viewAllCustomers
content-type: application/json

{
    "employeeID":"IEEE"
}


####
# Approve Customer Route
POST http://localhost:8000/employee/approveCustomer
content-type: application/json

{
    "id":"SFASFaSF",
    "employeeID":"IEEE"
}


####
# Approve Customer Route
POST http://localhost:8000/employee/rejectCustomer
content-type: application/json

{
    "id":"SFASFaSF",
    "employeeID":"IEEE"
}


####
# Approve Customer Route
POST http://localhost:8000/employee/activeCustomer
content-type: application/json

{
    "employeeID":"emp@emp.com"
}




#####################################################################################################
#                                                                                                   #
#                                          CUSTOMER ROTES                                           #
#                                                                                                   #
#####################################################################################################


# Root Customer Route
GET  http://localhost:8000/customer
content-type: application/json


####
# Register Customer Route
POST http://localhost:8000/customer/register
content-type: application/json

{
    "userName":"cus",
    "userID":"cus",
    "password":"123456",
    "grade":"sFsdg",
    "division":"sdgsdga",
    "instituteName":"agdd",
    "mailAddress":"sdgdsg@gmil.com",
    "adharNumber":1234564564,
    "contactNumber":1234566544,
    "fcmToken": "afafsfg"
}



#####################################################################################################
#                                                                                                   #
#                                          DRIVER ROTES                                             #
#                                                                                                   #
#####################################################################################################


####
# Register Driver Route
POST https://app-workbook.herokuapp.com/driver/register
content-type: application/json

{
    "userName":"driver",
    "userID":"driver",
    "password":"123456",
    "carNumber":"sFsdg",
    "instituteName":"IEEE",
    "adharNumber":1234564564,
    "contactNumber":1234566544,
    "fcmToken": "afafsfg"
}



#####################################################################################################
#                                                                                                   #
#                                          COMMON ROTES                                             #
#                                                                                                   #
#####################################################################################################

####
# Send Notifications
POST http://localhost:8000/sendNotification
content-type: application/json

{
    "fcmToken":"dItTSf1Lq5A:APA91bFhccnuE3JjCcCgdWtyuTU0UAeD7lgIRyhqY1_8x51kt1uJc2V-YHaKEBilFSv2yiKO8VetrBc790rrkp94_EmUd4JueoVEl38keHEsqJO_Rnco6r4bAolk7Tjdp2H_3n02gTRx",
    "message":"Approved"
}

####
# Login Route
POST http://localhost:8000/login
content-type: application/json

{
    "fcmToken" : "asdlkfccccccchdslf",
    "userID":"superAdmin@superAdmin",
    "password": "123"
}


####
# Upload Profile Picture Route
POST http://localhost:8000/uploadPicture
content-type: application/json

{
    "userID":"b@gmaiddl.com",
    "profilePicture": "sample.jpeg"
}



####
# Fetch User Profile Picture
GET  http://localhost:8000/getUserProfile/admin/5eec4a75a3d2575c7032728a
content-type: application/json



####
# Fetch Institute Profile Picture
GET  http://localhost:8000/fetchDivision/IEEE
content-type: application/json





####
POST http://localhost:8000/admin/setGD
content-type: application/json

{
    "instituteName": "IEEE",
    "division": [
        { "division": "zsd" },
        { "division": "2sdg" },
        { "division": "3zbsd" },
        { "division": "4Adgd" },
        { "division": "5gdsgdgd" }
    ],
    "grade": [
        { "grade": "hola" },
        { "grade": "V.chair" },
        { "grade": "TechHead" },
        { "grade": "SponHead" },
        { "grade": "TechLead" }
    ]
}





#####################################################################################################
#                                                                                                   #
#                                          POST ROTES                                               #
#                                                                                                   #
#####################################################################################################

####
# create Post
POST http://localhost:6000/post/createPost
content-type: application/json

{
    "id": "5ef5d361c4be2314e90a1b4f",
    "content": "new ssspost",
    "createdBy": "sdg",
    "mediaUrl": "dgGdsaag"
}



####
# delete Post
POST http://localhost:6000/post/deletePost
content-type: application/json

{
    "id": "5ef5d361c4be2314e90a1b4f"
}


####
# enable Post
POST http://localhost:6000/post/enablePost
content-type: application/json

{
    "id": "5ef5d361c4be2314e90a1b4f"
}



####
# disable Post
POST http://localhost:6000/post/disablePost
content-type: application/json

{
    "id": "5ef5d361c4be2314e90a1b4f"
}

####
# Update Post
POST http://localhost:6000/post/updatePost
content-type: application/json

{
    "id": "5ef5d361c4be2314e90a1b4f",
    "content": "newzxc s",
    "createdBy": "szxvdg",
    "mediaUrl": "ss"
}


####
# Fetch User Profile Picture
GET  http://localhost:6000/post/viewAllPost
content-type: application/json
