
#####################################################################################################
#                                                                                                   #
#                                          ADMIN ROTES                                              #
#                                                                                                   #
#####################################################################################################

# Root Admin Route
GET  http://localhost:8000/admin
content-type: application/json



####
# Register Admin Route
POST http://localhost:8000/admin/register
content-type: application/json

{
    "role":"Admin",
    "userName":"admin2",
    "userID":"sfdfdsddfsd.com",
    "password":"divyansh",
    "instituteName":"sdfsdddfsdfdd",
    "instituteType":"Chapter",
    "instituteImageUrl":"sample.jpeg",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "afafaaf"
}



####
# Get Organizations Route
GET  http://localhost:8000/admin/institutes
content-type: application/json


####
# View All Institute's Employee
POST http://localhost:8000/admin/viewAllEmployees
content-type: application/json

{
    "instituteName": "IEEE"
}



####
# Approve Employee
POST http://localhost:8000/admin/approveEmployee
content-type: application/json

{
    "id": "5eff862aab79eb61c5eb1423"
}



####
# Reject Employee
POST http://localhost:8000/admin/rejectEmployee
content-type: application/json

{
    "id": "5eef52404322216db5ec43a8"
}

####
# Delete Employee
POST http://localhost:8000/admin/deleteEmployee
content-type: application/json

{
    "id": "5eef66dceaad484382c4f4e9"
}



####
# Update Admin
POST http://localhost:8000/admin/update
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48",
    "userName":"admin2",
    "instituteType":"Chapter",
    "numberOfMembers":50,
    "state":"Tamil Nadu",
    "city":"Vellore",
    "mailAddress":"divyanshkhandelwal147@gmail.com",
    "adharNumber":123456789789,
    "contactNumber":9935071772,
    "fcmToken": "afafaaf"
}


####
# Approve Driver
POST http://localhost:8000/admin/approveDriver
content-type: application/json

{
    "id": "5eefa5187416ad00177c7127"
}




####
# Update Route
POST http://localhost:8000/admin/updateRoute
content-type: application/json

{
    "id": "5f0b561a92315a52456b70fb",
    "location": [{
      "latitude": 26.884910945492,
      "longitude": 75.83134130274,
      "name": "4-KA-6, Jaipur, Rajasthan, 302004, India"
    },
    {
      "latitude": 26.8849109448892,
      "longitude": 75.831349231774,
      "name": "4-KA-6, Marg, Jaipur, n, 302004, India"
    }],
    "routeName": "Route X",
    "userID": "rishi@admin.com",
    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJyaXNoaUBhZG1pbi5jb20iLCJpYXQiOjE1OTQ0NjU2Mjl9.-76LFHDcaEGYUHZ-c8LPia35eVQRg1Da7EPNAvszKpk"
}





####
# Update Route
POST http://localhost:8000/admin/deleteLocation
content-type: application/json

{
    
    "userID": "rishi@admin.com",
    "jwtToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJyaXNoaUBhZG1pbi5jb20iLCJpYXQiOjE1OTQ0NjU2Mjl9.-76LFHDcaEGYUHZ-c8LPia35eVQRg1Da7EPNAvszKpk"
}


