
#####################################################################################################
#                                                                                                   #
#                                         SUPER ADMIN ROTES                                         #
#                                                                                                   #
#####################################################################################################





####
# Test Route
GET  http://localhost:8000/superAdmin
content-type: application/json




####
# Create SuperAdmin
POST http://localhost:8000/superAdmin/create
content-type: application/json

{
    "fcmToken": "sdgsg",
    "userID": "superAdmin@gmail.com",
    "password": "123",
    "userName": "superAdmin"
}



####
# Purge the Database
DELETE http://localhost:8000/superAdmin/purge
content-type: application/json


####
# Approve Admin
POST http://localhost:8000/superAdmin/approveAdmin
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48"
}

####
# Delete Admin
DELETE  http://localhost:8000/superAdmin/deleteAdmin
content-type: application/json

{
    "id": "5eef64e2e59e040017aded48"
}



####
# Login Route
POST http://localhost:8000/login
content-type: application/json

{
    "fcmToken" : "asdlkfccccccchdslf",
    "userID":"superAdmin",
    "password": "123"
}



















####
POST https://hooks.spike.sh/ca621a74920dd44e03e8/push-events
content-type: application/json

{
    "check_id": "1234565432",
    "message": "Test is DOWn",
    "title": "Test is DOWn",
    "status": "DOWN"
}



####
POST https://hooks.spike.sh/ca621a74920dd44e03e8/push-events
content-type: application/json

{
    "check_id": "1234565432",
    "message": "Test is UP",
    "title": "Test is UP",
    "status": "UP"
}